import { storage } from "./storage";

interface DestinationData {
  name: string;
  state: string;
  shortDescription: string;
  detailedInsight?: string;
  highlights?: string[];
  imageUrl?: string;
  bestSeason?: string;
  isFeatured?: boolean;
  featuredDate?: Date;
}

const DEFAULT_IMAGE = "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800";

function generateDetailedInsight(name: string, state: string, shortDescription: string): string {
  return `${name} is a captivating destination in ${state}. ${shortDescription}. This destination offers travelers a unique blend of culture, history, and natural beauty. Whether you're seeking adventure, relaxation, or cultural immersion, ${name} has something special to offer every visitor.`;
}

function generateHighlights(shortDescription: string): string[] {
  const highlights = [
    "Rich cultural heritage",
    "Local cuisine",
    "Warm hospitality"
  ];
  if (shortDescription.toLowerCase().includes("temple") || shortDescription.toLowerCase().includes("pilgrimage")) {
    highlights.push("Religious significance");
  }
  if (shortDescription.toLowerCase().includes("beach")) {
    highlights.push("Beautiful beaches");
  }
  if (shortDescription.toLowerCase().includes("hill") || shortDescription.toLowerCase().includes("mountain")) {
    highlights.push("Scenic mountain views");
  }
  if (shortDescription.toLowerCase().includes("fort") || shortDescription.toLowerCase().includes("palace")) {
    highlights.push("Historic architecture");
  }
  if (shortDescription.toLowerCase().includes("wildlife") || shortDescription.toLowerCase().includes("tiger") || shortDescription.toLowerCase().includes("sanctuary")) {
    highlights.push("Wildlife experiences");
  }
  return highlights;
}

const destinationsData: DestinationData[] = [
  // FEATURED DESTINATIONS
  {
    name: "Goa",
    state: "Goa",
    shortDescription: "Golden beaches, Portuguese heritage, and vibrant nightlife",
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    bestSeason: "November to March",
    isFeatured: true,
    featuredDate: new Date(),
  },
  {
    name: "Kerala",
    state: "Kerala",
    shortDescription: "God's Own Country with serene backwaters and lush tea estates",
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    bestSeason: "October to March",
    isFeatured: true,
    featuredDate: new Date(),
  },
  {
    name: "Jaipur",
    state: "Rajasthan",
    shortDescription: "The Pink City featuring magnificent forts and palaces",
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800",
    bestSeason: "October to March",
    isFeatured: true,
    featuredDate: new Date(),
  },
  
  // ANDHRA PRADESH
  { name: "Hyderabad", state: "Telangana", shortDescription: "City of Pearls with historic monuments and biryani" },
  { name: "Visakhapatnam", state: "Andhra Pradesh", shortDescription: "Port city with beautiful beaches and hills" },
  { name: "Vijayawada", state: "Andhra Pradesh", shortDescription: "Cultural hub on the banks of Krishna River" },
  { name: "Tirupati", state: "Andhra Pradesh", shortDescription: "Famous pilgrimage destination with Sri Venkateswara Temple" },
  { name: "Guntur", state: "Andhra Pradesh", shortDescription: "Historic city known for chili trade" },
  { name: "Nellore", state: "Andhra Pradesh", shortDescription: "Ancient town with temples and beaches" },
  { name: "Kurnool", state: "Andhra Pradesh", shortDescription: "Gateway to Belum Caves" },
  { name: "Rajahmundry", state: "Andhra Pradesh", shortDescription: "Cultural capital on Godavari banks" },
  { name: "Kakinada", state: "Andhra Pradesh", shortDescription: "Beach town with Hope Island" },
  { name: "Anantapur", state: "Andhra Pradesh", shortDescription: "Historic town with Lepakshi Temple nearby" },
  { name: "Kadapa", state: "Andhra Pradesh", shortDescription: "Known for religious sites and mining" },
  { name: "Srikakulam", state: "Andhra Pradesh", shortDescription: "Temple town with ancient heritage" },
  { name: "Eluru", state: "Andhra Pradesh", shortDescription: "Known for carpets and handlooms" },
  { name: "Ongole", state: "Andhra Pradesh", shortDescription: "Famous for Ongole cattle breed" },
  { name: "Chittoor", state: "Andhra Pradesh", shortDescription: "Gateway to Tirumala hills" },
  { name: "Machilipatnam", state: "Andhra Pradesh", shortDescription: "Historic port with Kalamkari art" },
  { name: "Tenali", state: "Andhra Pradesh", shortDescription: "Rice bowl of Andhra Pradesh" },
  { name: "Proddatur", state: "Andhra Pradesh", shortDescription: "Historic town with temples" },
  { name: "Hindupur", state: "Andhra Pradesh", shortDescription: "Gateway to Penukonda Fort" },
  { name: "Tadepalligudem", state: "Andhra Pradesh", shortDescription: "Agricultural hub in West Godavari" },
  { name: "Narasaraopet", state: "Andhra Pradesh", shortDescription: "Historic town with Kotappakonda Temple" },
  { name: "Vizianagaram", state: "Andhra Pradesh", shortDescription: "Fort city with rich history" },
  { name: "Amaravati", state: "Andhra Pradesh", shortDescription: "New capital with Buddhist heritage" },
  
  // ARUNACHAL PRADESH
  { name: "Itanagar", state: "Arunachal Pradesh", shortDescription: "Capital city with Ita Fort ruins" },
  { name: "Tawang", state: "Arunachal Pradesh", shortDescription: "Buddhist monastery town near Tibet border" },
  { name: "Ziro", state: "Arunachal Pradesh", shortDescription: "UNESCO heritage site with Apatani tribe" },
  { name: "Pasighat", state: "Arunachal Pradesh", shortDescription: "Oldest town with Siang River" },
  { name: "Bomdila", state: "Arunachal Pradesh", shortDescription: "Hill station with Buddhist monasteries" },
  { name: "Along", state: "Arunachal Pradesh", shortDescription: "Tribal town with hanging bridges" },
  { name: "Tezu", state: "Arunachal Pradesh", shortDescription: "Gateway to Glow Lake" },
  { name: "Naharlagun", state: "Arunachal Pradesh", shortDescription: "Twin city of Itanagar" },
  { name: "Roing", state: "Arunachal Pradesh", shortDescription: "Gateway to Mehao Wildlife Sanctuary" },
  { name: "Anini", state: "Arunachal Pradesh", shortDescription: "Remote town with pristine nature" },
  { name: "Dirang", state: "Arunachal Pradesh", shortDescription: "Valley town with hot springs" },
  { name: "Seppa", state: "Arunachal Pradesh", shortDescription: "District headquarters of East Kameng" },
  { name: "Daporijo", state: "Arunachal Pradesh", shortDescription: "Town on Subansiri River banks" },
  
  // ASSAM
  { name: "Guwahati", state: "Assam", shortDescription: "Gateway to Northeast India with Kamakhya Temple" },
  { name: "Jorhat", state: "Assam", shortDescription: "Tea capital with Majuli Island nearby" },
  { name: "Dibrugarh", state: "Assam", shortDescription: "Tea city of Assam" },
  { name: "Silchar", state: "Assam", shortDescription: "Gateway to Barak Valley" },
  { name: "Tezpur", state: "Assam", shortDescription: "Cultural capital with scenic beauty" },
  { name: "Nagaon", state: "Assam", shortDescription: "Historic town with Kaziranga nearby" },
  { name: "Tinsukia", state: "Assam", shortDescription: "Gateway to Dibru-Saikhowa" },
  { name: "Bongaigaon", state: "Assam", shortDescription: "Industrial town with Manas nearby" },
  { name: "Sibsagar", state: "Assam", shortDescription: "Ahom dynasty capital with heritage sites" },
  { name: "Majuli", state: "Assam", shortDescription: "World's largest river island" },
  { name: "Kaziranga", state: "Assam", shortDescription: "UNESCO site famous for one-horned rhinos" },
  { name: "Barpeta", state: "Assam", shortDescription: "Religious town with satras" },
  { name: "Goalpara", state: "Assam", shortDescription: "Gateway to Manas National Park" },
  { name: "Haflong", state: "Assam", shortDescription: "Only hill station of Assam" },
  { name: "Diphu", state: "Assam", shortDescription: "Karbi Anglong district headquarters" },
  { name: "Dhubri", state: "Assam", shortDescription: "Border town on Brahmaputra" },
  { name: "Nalbari", state: "Assam", shortDescription: "Agricultural hub of lower Assam" },
  
  // BIHAR
  { name: "Patna", state: "Bihar", shortDescription: "Ancient capital on the Ganges with rich history" },
  { name: "Gaya", state: "Bihar", shortDescription: "Sacred city with Bodh Gaya nearby" },
  { name: "Bodh Gaya", state: "Bihar", shortDescription: "Where Buddha attained enlightenment" },
  { name: "Muzaffarpur", state: "Bihar", shortDescription: "Known for litchis and education" },
  { name: "Bhagalpur", state: "Bihar", shortDescription: "Silk city on the Ganges" },
  { name: "Darbhanga", state: "Bihar", shortDescription: "Cultural hub of Mithila region" },
  { name: "Purnia", state: "Bihar", shortDescription: "Gateway to Nepal border" },
  { name: "Nalanda", state: "Bihar", shortDescription: "Ancient university ruins UNESCO site" },
  { name: "Rajgir", state: "Bihar", shortDescription: "Ancient city with hot springs" },
  { name: "Sasaram", state: "Bihar", shortDescription: "Tomb of Sher Shah Suri" },
  { name: "Vaishali", state: "Bihar", shortDescription: "Ancient republic and Buddhist site" },
  { name: "Araria", state: "Bihar", shortDescription: "Border town near Nepal" },
  { name: "Begusarai", state: "Bihar", shortDescription: "Industrial town with refineries" },
  { name: "Bihar Sharif", state: "Bihar", shortDescription: "Historic town with Sufi shrines" },
  { name: "Chhapra", state: "Bihar", shortDescription: "Town on Ganga-Ghaghara confluence" },
  { name: "Hajipur", state: "Bihar", shortDescription: "Famous for banana cultivation" },
  { name: "Katihar", state: "Bihar", shortDescription: "Railway junction town" },
  { name: "Madhubani", state: "Bihar", shortDescription: "Famous for Madhubani paintings" },
  { name: "Motihari", state: "Bihar", shortDescription: "Associated with Mahatma Gandhi" },
  { name: "Saharsa", state: "Bihar", shortDescription: "Town in Kosi region" },
  { name: "Sitamarhi", state: "Bihar", shortDescription: "Birthplace of Goddess Sita" },
  { name: "Siwan", state: "Bihar", shortDescription: "Historic town with sugar mills" },
  
  // CHHATTISGARH
  { name: "Raipur", state: "Chhattisgarh", shortDescription: "Capital city with lakes and temples" },
  { name: "Bhilai", state: "Chhattisgarh", shortDescription: "Steel city of India" },
  { name: "Bilaspur", state: "Chhattisgarh", shortDescription: "Judicial capital with Achanakmar" },
  { name: "Korba", state: "Chhattisgarh", shortDescription: "Power capital of Chhattisgarh" },
  { name: "Durg", state: "Chhattisgarh", shortDescription: "Industrial hub with ancient temples" },
  { name: "Jagdalpur", state: "Chhattisgarh", shortDescription: "Gateway to Chitrakote Falls" },
  { name: "Raigarh", state: "Chhattisgarh", shortDescription: "Cultural capital with music tradition" },
  { name: "Ambikapur", state: "Chhattisgarh", shortDescription: "Cleanest city with tribal culture" },
  { name: "Chitrakote", state: "Chhattisgarh", shortDescription: "Niagara Falls of India" },
  { name: "Dhamtari", state: "Chhattisgarh", shortDescription: "Rice bowl with Gangrel Dam" },
  { name: "Rajnandgaon", state: "Chhattisgarh", shortDescription: "Industrial town with handlooms" },
  { name: "Kawardha", state: "Chhattisgarh", shortDescription: "Royal heritage with palace" },
  { name: "Dongargarh", state: "Chhattisgarh", shortDescription: "Pilgrimage with Maa Bamleshwari Temple" },
  { name: "Mahasamund", state: "Chhattisgarh", shortDescription: "Agricultural hub with temples" },
  { name: "Surguja", state: "Chhattisgarh", shortDescription: "Tribal region with natural beauty" },
  { name: "Bastar", state: "Chhattisgarh", shortDescription: "Tribal heartland with Dussehra" },
  
  // GOA
  { name: "Panaji", state: "Goa", shortDescription: "Capital city with Portuguese architecture" },
  { name: "Margao", state: "Goa", shortDescription: "Commercial hub of South Goa" },
  { name: "Vasco da Gama", state: "Goa", shortDescription: "Port city with Mormugao harbor" },
  { name: "Mapusa", state: "Goa", shortDescription: "Friday market town in North Goa" },
  { name: "Ponda", state: "Goa", shortDescription: "Temple town with spice plantations" },
  { name: "Calangute", state: "Goa", shortDescription: "Queen of beaches" },
  { name: "Baga", state: "Goa", shortDescription: "Party beach destination" },
  { name: "Anjuna", state: "Goa", shortDescription: "Famous flea market and nightlife" },
  { name: "Candolim", state: "Goa", shortDescription: "Serene beach with water sports" },
  { name: "Palolem", state: "Goa", shortDescription: "Crescent shaped beach paradise" },
  { name: "Arambol", state: "Goa", shortDescription: "Hippie beach with sweet water lake" },
  { name: "Vagator", state: "Goa", shortDescription: "Cliff beach with Chapora Fort" },
  { name: "Morjim", state: "Goa", shortDescription: "Turtle nesting beach" },
  { name: "Colva", state: "Goa", shortDescription: "Popular beach in South Goa" },
  { name: "Old Goa", state: "Goa", shortDescription: "UNESCO churches and cathedrals" },
  { name: "Benaulim", state: "Goa", shortDescription: "Quiet beach village in South Goa" },
  { name: "Agonda", state: "Goa", shortDescription: "Pristine beach with dolphins" },
  { name: "Cavelossim", state: "Goa", shortDescription: "Upscale beach destination" },
  { name: "Dudhsagar", state: "Goa", shortDescription: "Famous waterfall on Karnataka border" },
  { name: "Sinquerim", state: "Goa", shortDescription: "Beach with Aguada Fort" },
  
  // GUJARAT
  { name: "Ahmedabad", state: "Gujarat", shortDescription: "UNESCO heritage city with rich textile history" },
  { name: "Surat", state: "Gujarat", shortDescription: "Diamond city and textile hub" },
  { name: "Vadodara", state: "Gujarat", shortDescription: "Cultural capital with Laxmi Vilas Palace" },
  { name: "Rajkot", state: "Gujarat", shortDescription: "City associated with Mahatma Gandhi" },
  { name: "Bhavnagar", state: "Gujarat", shortDescription: "Gateway to Palitana temples" },
  { name: "Jamnagar", state: "Gujarat", shortDescription: "Jewel of Kathiawad with marine park" },
  { name: "Junagadh", state: "Gujarat", shortDescription: "Historic city with Gir Forest nearby" },
  { name: "Gandhinagar", state: "Gujarat", shortDescription: "Planned capital with Akshardham" },
  { name: "Kutch", state: "Gujarat", shortDescription: "Rann of Kutch white desert" },
  { name: "Dwarka", state: "Gujarat", shortDescription: "Sacred pilgrimage on Arabian Sea" },
  { name: "Somnath", state: "Gujarat", shortDescription: "Ancient Jyotirlinga temple" },
  { name: "Gir", state: "Gujarat", shortDescription: "Only home of Asiatic lions" },
  { name: "Diu", state: "Gujarat", shortDescription: "Beach destination with Portuguese heritage" },
  { name: "Saputara", state: "Gujarat", shortDescription: "Only hill station in Gujarat" },
  { name: "Statue of Unity", state: "Gujarat", shortDescription: "World's tallest statue" },
  { name: "Porbandar", state: "Gujarat", shortDescription: "Birthplace of Mahatma Gandhi" },
  { name: "Bhuj", state: "Gujarat", shortDescription: "Gateway to Rann of Kutch" },
  { name: "Palitana", state: "Gujarat", shortDescription: "City of temples on Shatrunjaya hill" },
  { name: "Modhera", state: "Gujarat", shortDescription: "Famous Sun Temple" },
  { name: "Patan", state: "Gujarat", shortDescription: "UNESCO Rani ki Vav stepwell" },
  { name: "Anand", state: "Gujarat", shortDescription: "Milk capital of India" },
  { name: "Navsari", state: "Gujarat", shortDescription: "Historic Parsi settlement" },
  { name: "Morbi", state: "Gujarat", shortDescription: "Ceramic tile hub" },
  { name: "Veraval", state: "Gujarat", shortDescription: "Fishing port near Somnath" },
  { name: "Mehsana", state: "Gujarat", shortDescription: "Gateway to Modhera Sun Temple" },
  { name: "Nadiad", state: "Gujarat", shortDescription: "Pilgrimage town with Santram Mandir" },
  { name: "Surendranagar", state: "Gujarat", shortDescription: "Gateway to Little Rann" },
  { name: "Bharuch", state: "Gujarat", shortDescription: "Ancient port on Narmada River" },
  { name: "Valsad", state: "Gujarat", shortDescription: "Southern coastal district" },
  { name: "Godhra", state: "Gujarat", shortDescription: "Historic town in Panchmahal" },
  { name: "Mandvi", state: "Gujarat", shortDescription: "Beach town with ship building" },
  { name: "Adalaj", state: "Gujarat", shortDescription: "Famous stepwell architecture" },
  { name: "Lothal", state: "Gujarat", shortDescription: "Indus Valley Civilization site" },
  { name: "Champaner", state: "Gujarat", shortDescription: "UNESCO archaeological park" },
  { name: "Pavagadh", state: "Gujarat", shortDescription: "Pilgrimage with Kalika Mata Temple" },
  
  // HARYANA
  { name: "Gurugram", state: "Haryana", shortDescription: "Millennium City and IT hub" },
  { name: "Faridabad", state: "Haryana", shortDescription: "Industrial city near Delhi" },
  { name: "Chandigarh", state: "Haryana", shortDescription: "Planned city capital shared with Punjab" },
  { name: "Panipat", state: "Haryana", shortDescription: "City of weavers and historic battles" },
  { name: "Ambala", state: "Haryana", shortDescription: "Gateway to Himachal Pradesh" },
  { name: "Karnal", state: "Haryana", shortDescription: "Rice bowl of India" },
  { name: "Hisar", state: "Haryana", shortDescription: "Steel city with ancient ruins" },
  { name: "Rohtak", state: "Haryana", shortDescription: "Heart of Haryana" },
  { name: "Sonipat", state: "Haryana", shortDescription: "Industrial hub near NCR" },
  { name: "Kurukshetra", state: "Haryana", shortDescription: "Land of Mahabharata war" },
  { name: "Panchkula", state: "Haryana", shortDescription: "Planned city with Morni Hills" },
  { name: "Yamunanagar", state: "Haryana", shortDescription: "Paper industry hub" },
  { name: "Bhiwani", state: "Haryana", shortDescription: "Wrestling hub with boxers" },
  { name: "Jind", state: "Haryana", shortDescription: "Ancient town with temples" },
  { name: "Kaithal", state: "Haryana", shortDescription: "Historic town with baolis" },
  { name: "Palwal", state: "Haryana", shortDescription: "Agricultural town near Delhi" },
  { name: "Rewari", state: "Haryana", shortDescription: "Brass industry center" },
  { name: "Sirsa", state: "Haryana", shortDescription: "Cotton growing region" },
  { name: "Morni Hills", state: "Haryana", shortDescription: "Only hill station in Haryana" },
  { name: "Sultanpur", state: "Haryana", shortDescription: "Bird sanctuary near Gurugram" },
  
  // HIMACHAL PRADESH
  { name: "Shimla", state: "Himachal Pradesh", shortDescription: "Queen of Hills and former summer capital" },
  { name: "Manali", state: "Himachal Pradesh", shortDescription: "Adventure capital with snow-capped peaks" },
  { name: "Dharamshala", state: "Himachal Pradesh", shortDescription: "Home of Dalai Lama and McLeodganj" },
  { name: "Kullu", state: "Himachal Pradesh", shortDescription: "Valley of Gods with Dussehra festival" },
  { name: "Dalhousie", state: "Himachal Pradesh", shortDescription: "Colonial hill station with pine forests" },
  { name: "Kasol", state: "Himachal Pradesh", shortDescription: "Mini Israel of India in Parvati Valley" },
  { name: "Spiti Valley", state: "Himachal Pradesh", shortDescription: "Cold desert mountain valley" },
  { name: "Bir Billing", state: "Himachal Pradesh", shortDescription: "Paragliding capital of India" },
  { name: "Chamba", state: "Himachal Pradesh", shortDescription: "Ancient kingdom with temples" },
  { name: "Kangra", state: "Himachal Pradesh", shortDescription: "Valley known for paintings and tea" },
  { name: "Kinnaur", state: "Himachal Pradesh", shortDescription: "Land of fairies and apples" },
  { name: "Khajjiar", state: "Himachal Pradesh", shortDescription: "Mini Switzerland of India" },
  { name: "Mcleodganj", state: "Himachal Pradesh", shortDescription: "Little Lhasa with Tibetan culture" },
  { name: "Kufri", state: "Himachal Pradesh", shortDescription: "Ski resort near Shimla" },
  { name: "Solang Valley", state: "Himachal Pradesh", shortDescription: "Adventure sports hub near Manali" },
  { name: "Rohtang Pass", state: "Himachal Pradesh", shortDescription: "High mountain pass to Lahaul" },
  { name: "Tirthan Valley", state: "Himachal Pradesh", shortDescription: "Offbeat destination with trout fishing" },
  { name: "Jibhi", state: "Himachal Pradesh", shortDescription: "Serene village in Tirthan Valley" },
  { name: "Malana", state: "Himachal Pradesh", shortDescription: "Ancient village with unique culture" },
  { name: "Narkanda", state: "Himachal Pradesh", shortDescription: "Apple orchards and skiing" },
  { name: "Palampur", state: "Himachal Pradesh", shortDescription: "Tea capital of North India" },
  { name: "Barot", state: "Himachal Pradesh", shortDescription: "Offbeat valley with trout fishing" },
  { name: "Chitkul", state: "Himachal Pradesh", shortDescription: "Last inhabited village near Tibet" },
  { name: "Kalpa", state: "Himachal Pradesh", shortDescription: "Kinner Kailash views and apples" },
  { name: "Sangla Valley", state: "Himachal Pradesh", shortDescription: "Beautiful valley in Kinnaur" },
  { name: "Manikaran", state: "Himachal Pradesh", shortDescription: "Hot springs and Sikh shrine" },
  { name: "Prashar Lake", state: "Himachal Pradesh", shortDescription: "Sacred lake with floating island" },
  { name: "Kaza", state: "Himachal Pradesh", shortDescription: "Headquarters of Spiti Valley" },
  { name: "Tabo", state: "Himachal Pradesh", shortDescription: "Ajanta of Himalayas monastery" },
  { name: "Key Monastery", state: "Himachal Pradesh", shortDescription: "Largest monastery in Spiti" },
  { name: "Triund", state: "Himachal Pradesh", shortDescription: "Popular trek near Dharamshala" },
  { name: "Solan", state: "Himachal Pradesh", shortDescription: "Mushroom capital with breweries" },
  { name: "Mandi", state: "Himachal Pradesh", shortDescription: "Gateway to Kullu and Dharamshala" },
  { name: "Bilaspur", state: "Himachal Pradesh", shortDescription: "Gobind Sagar Lake destination" },
  { name: "Una", state: "Himachal Pradesh", shortDescription: "Gateway to Himachal from Punjab" },
  { name: "Hamirpur", state: "Himachal Pradesh", shortDescription: "Most literate district in India" },
  { name: "Nahan", state: "Himachal Pradesh", shortDescription: "Capital of Sirmaur with Renuka Lake" },
  { name: "Sarahan", state: "Himachal Pradesh", shortDescription: "Bhimakali Temple and views" },
  { name: "Tattapani", state: "Himachal Pradesh", shortDescription: "Hot springs on Sutlej banks" },
  { name: "Chail", state: "Himachal Pradesh", shortDescription: "Highest cricket ground location" },
  
  // JHARKHAND
  { name: "Ranchi", state: "Jharkhand", shortDescription: "City of waterfalls and capital" },
  { name: "Jamshedpur", state: "Jharkhand", shortDescription: "Steel city founded by Tatas" },
  { name: "Dhanbad", state: "Jharkhand", shortDescription: "Coal capital of India" },
  { name: "Bokaro", state: "Jharkhand", shortDescription: "Steel city with Bokaro Steel Plant" },
  { name: "Deoghar", state: "Jharkhand", shortDescription: "Sacred town with Baidyanath Temple" },
  { name: "Hazaribagh", state: "Jharkhand", shortDescription: "Wildlife sanctuary and hill station" },
  { name: "Giridih", state: "Jharkhand", shortDescription: "Known for mica and Jain temples" },
  { name: "Netarhat", state: "Jharkhand", shortDescription: "Queen of Chotanagpur" },
  { name: "Betla", state: "Jharkhand", shortDescription: "National park with tigers" },
  { name: "Hundru Falls", state: "Jharkhand", shortDescription: "Highest waterfall in Jharkhand" },
  { name: "Parasnath", state: "Jharkhand", shortDescription: "Highest peak and Jain pilgrimage" },
  { name: "Dalma", state: "Jharkhand", shortDescription: "Wildlife sanctuary with elephants" },
  { name: "Rajmahal", state: "Jharkhand", shortDescription: "Historic town on Ganges" },
  { name: "Chandil", state: "Jharkhand", shortDescription: "Dam and water sports" },
  { name: "McCluskieganj", state: "Jharkhand", shortDescription: "Anglo-Indian heritage town" },
  
  // KARNATAKA
  { name: "Bengaluru", state: "Karnataka", shortDescription: "Silicon Valley of India with pleasant weather" },
  { name: "Mysuru", state: "Karnataka", shortDescription: "City of Palaces with Dasara festival" },
  { name: "Mangaluru", state: "Karnataka", shortDescription: "Port city with beautiful beaches" },
  { name: "Hubli", state: "Karnataka", shortDescription: "Commercial capital of North Karnataka" },
  { name: "Belgaum", state: "Karnataka", shortDescription: "Military hub near Western Ghats" },
  { name: "Hampi", state: "Karnataka", shortDescription: "UNESCO site of Vijayanagara Empire" },
  { name: "Coorg", state: "Karnataka", shortDescription: "Scotland of India with coffee estates" },
  { name: "Gokarna", state: "Karnataka", shortDescription: "Beach town with Om Beach" },
  { name: "Udupi", state: "Karnataka", shortDescription: "Temple town famous for cuisine" },
  { name: "Badami", state: "Karnataka", shortDescription: "Cave temples of Chalukyas" },
  { name: "Chikmagalur", state: "Karnataka", shortDescription: "Coffee land with Mullayanagiri peak" },
  { name: "Dandeli", state: "Karnataka", shortDescription: "Adventure hub with river rafting" },
  { name: "Kabini", state: "Karnataka", shortDescription: "Wildlife safari destination" },
  { name: "Bandipur", state: "Karnataka", shortDescription: "Tiger reserve in Nilgiris" },
  { name: "Shivanasamudra", state: "Karnataka", shortDescription: "Segmented waterfall on Kaveri" },
  { name: "Nandi Hills", state: "Karnataka", shortDescription: "Sunrise point near Bangalore" },
  { name: "Bijapur", state: "Karnataka", shortDescription: "Gol Gumbaz and Islamic architecture" },
  { name: "Shravanabelagola", state: "Karnataka", shortDescription: "Jain pilgrimage with Gommateshwara" },
  { name: "Murudeshwar", state: "Karnataka", shortDescription: "Temple with world's second tallest Shiva" },
  { name: "Agumbe", state: "Karnataka", shortDescription: "Cherrapunji of South India" },
  { name: "Davangere", state: "Karnataka", shortDescription: "Famous for Benne Dosa" },
  { name: "Chitradurga", state: "Karnataka", shortDescription: "Stone fortress and history" },
  { name: "Karwar", state: "Karnataka", shortDescription: "Beach town and naval base" },
  { name: "Jog Falls", state: "Karnataka", shortDescription: "Second highest plunge waterfall" },
  { name: "Pattadakal", state: "Karnataka", shortDescription: "UNESCO Chalukyan temples" },
  { name: "Aihole", state: "Karnataka", shortDescription: "Cradle of Indian temple architecture" },
  { name: "Hassan", state: "Karnataka", shortDescription: "Gateway to Belur and Halebidu" },
  { name: "Belur", state: "Karnataka", shortDescription: "Hoysala temple architecture" },
  { name: "Halebidu", state: "Karnataka", shortDescription: "Hoysala capital with temples" },
  { name: "Srirangapatna", state: "Karnataka", shortDescription: "Tipu Sultan's capital" },
  { name: "Melukote", state: "Karnataka", shortDescription: "Temple town on hills" },
  { name: "Channapatna", state: "Karnataka", shortDescription: "Toy town with wooden crafts" },
  { name: "Shimoga", state: "Karnataka", shortDescription: "Gateway to Jog Falls" },
  { name: "Raichur", state: "Karnataka", shortDescription: "Historic fort city" },
  { name: "Gulbarga", state: "Karnataka", shortDescription: "Historic city with fort" },
  { name: "BR Hills", state: "Karnataka", shortDescription: "Biligiriranga Hills wildlife" },
  { name: "Sakleshpur", state: "Karnataka", shortDescription: "Coffee estates and trekking" },
  { name: "Kudremukh", state: "Karnataka", shortDescription: "National park and trekking" },
  { name: "Bhadra", state: "Karnataka", shortDescription: "Tiger reserve with safari" },
  { name: "Nagarhole", state: "Karnataka", shortDescription: "Rajiv Gandhi National Park" },
  
  // KERALA
  { name: "Thiruvananthapuram", state: "Kerala", shortDescription: "Capital city with Padmanabhaswamy Temple" },
  { name: "Kochi", state: "Kerala", shortDescription: "Queen of Arabian Sea with colonial heritage" },
  { name: "Kozhikode", state: "Kerala", shortDescription: "City of spices where Vasco da Gama landed" },
  { name: "Thrissur", state: "Kerala", shortDescription: "Cultural capital with Pooram festival" },
  { name: "Alleppey", state: "Kerala", shortDescription: "Venice of the East with backwaters" },
  { name: "Munnar", state: "Kerala", shortDescription: "Tea gardens in the clouds" },
  { name: "Thekkady", state: "Kerala", shortDescription: "Periyar Wildlife Sanctuary" },
  { name: "Kovalam", state: "Kerala", shortDescription: "Beach resort with lighthouse" },
  { name: "Varkala", state: "Kerala", shortDescription: "Cliff beach with mineral springs" },
  { name: "Wayanad", state: "Kerala", shortDescription: "Hill district with wildlife and waterfalls" },
  { name: "Kumarakom", state: "Kerala", shortDescription: "Backwater resort destination" },
  { name: "Bekal", state: "Kerala", shortDescription: "Beach fort in North Kerala" },
  { name: "Kannur", state: "Kerala", shortDescription: "Land of looms and lores" },
  { name: "Athirapally", state: "Kerala", shortDescription: "Niagara of India waterfall" },
  { name: "Fort Kochi", state: "Kerala", shortDescription: "Historic quarter with Chinese nets" },
  { name: "Marari", state: "Kerala", shortDescription: "Secluded beach destination" },
  { name: "Vagamon", state: "Kerala", shortDescription: "Hill station with meadows" },
  { name: "Kollam", state: "Kerala", shortDescription: "Cashew capital and backwaters" },
  { name: "Palakkad", state: "Kerala", shortDescription: "Gateway of Kerala with fort" },
  { name: "Guruvayur", state: "Kerala", shortDescription: "Sacred Krishna Temple town" },
  { name: "Kottayam", state: "Kerala", shortDescription: "Land of letters and rubber" },
  { name: "Poovar", state: "Kerala", shortDescription: "Backwater island destination" },
  { name: "Cherai", state: "Kerala", shortDescription: "Beach near Kochi" },
  { name: "Alappuzha", state: "Kerala", shortDescription: "Houseboat capital of Kerala" },
  { name: "Malappuram", state: "Kerala", shortDescription: "Football hub of Kerala" },
  { name: "Kasaragod", state: "Kerala", shortDescription: "Northernmost district with forts" },
  { name: "Idukki", state: "Kerala", shortDescription: "Arch dam and hill stations" },
  { name: "Nelliampathy", state: "Kerala", shortDescription: "Mini Ooty of Kerala" },
  { name: "Silent Valley", state: "Kerala", shortDescription: "Last evergreen tropical forest" },
  { name: "Ponmudi", state: "Kerala", shortDescription: "Golden peak hill station" },
  
  // LADAKH
  { name: "Leh", state: "Ladakh", shortDescription: "High-altitude desert capital with monasteries" },
  { name: "Pangong Lake", state: "Ladakh", shortDescription: "Blue lake extending to Tibet" },
  { name: "Nubra Valley", state: "Ladakh", shortDescription: "Cold desert with Bactrian camels" },
  { name: "Tso Moriri", state: "Ladakh", shortDescription: "High altitude lake in Changthang" },
  { name: "Kargil", state: "Ladakh", shortDescription: "Gateway to Zanskar" },
  { name: "Zanskar", state: "Ladakh", shortDescription: "Remote valley with frozen river trek" },
  { name: "Khardung La", state: "Ladakh", shortDescription: "One of highest motorable passes" },
  { name: "Hemis", state: "Ladakh", shortDescription: "Famous monastery with festival" },
  { name: "Lamayuru", state: "Ladakh", shortDescription: "Moonland landscape monastery" },
  { name: "Diskit", state: "Ladakh", shortDescription: "Monastery with giant Buddha statue" },
  { name: "Thiksey", state: "Ladakh", shortDescription: "Mini Potala Palace monastery" },
  { name: "Shey", state: "Ladakh", shortDescription: "Ancient capital with palace" },
  { name: "Alchi", state: "Ladakh", shortDescription: "Ancient monastery with murals" },
  { name: "Likir", state: "Ladakh", shortDescription: "Monastery with giant Buddha" },
  { name: "Stok", state: "Ladakh", shortDescription: "Royal palace and museum" },
  { name: "Changthang", state: "Ladakh", shortDescription: "High altitude plateau with nomads" },
  { name: "Turtuk", state: "Ladakh", shortDescription: "Northernmost village of India" },
  { name: "Hanle", state: "Ladakh", shortDescription: "Dark sky reserve for stargazing" },
  
  // MADHYA PRADESH
  { name: "Bhopal", state: "Madhya Pradesh", shortDescription: "City of Lakes and capital" },
  { name: "Indore", state: "Madhya Pradesh", shortDescription: "Commercial capital and food paradise" },
  { name: "Jabalpur", state: "Madhya Pradesh", shortDescription: "Marble Rocks and Dhuandhar Falls" },
  { name: "Gwalior", state: "Madhya Pradesh", shortDescription: "Fort city with musical heritage" },
  { name: "Ujjain", state: "Madhya Pradesh", shortDescription: "Ancient city of Kumbh Mela" },
  { name: "Khajuraho", state: "Madhya Pradesh", shortDescription: "UNESCO temples with erotic sculptures" },
  { name: "Sanchi", state: "Madhya Pradesh", shortDescription: "UNESCO Buddhist stupas" },
  { name: "Orchha", state: "Madhya Pradesh", shortDescription: "Medieval town with Bundela palaces" },
  { name: "Pachmarhi", state: "Madhya Pradesh", shortDescription: "Queen of Satpura hills" },
  { name: "Kanha", state: "Madhya Pradesh", shortDescription: "Tiger reserve inspiration for Jungle Book" },
  { name: "Bandhavgarh", state: "Madhya Pradesh", shortDescription: "Highest tiger density park" },
  { name: "Pench", state: "Madhya Pradesh", shortDescription: "Tiger reserve on MP-Maharashtra border" },
  { name: "Mandu", state: "Madhya Pradesh", shortDescription: "Romantic ruins of Afghan architecture" },
  { name: "Omkareshwar", state: "Madhya Pradesh", shortDescription: "Om-shaped island Jyotirlinga" },
  { name: "Maheshwar", state: "Madhya Pradesh", shortDescription: "Temple town on Narmada with sarees" },
  { name: "Bhimbetka", state: "Madhya Pradesh", shortDescription: "UNESCO rock shelters with cave paintings" },
  { name: "Satna", state: "Madhya Pradesh", shortDescription: "Gateway to Chitrakoot" },
  { name: "Rewa", state: "Madhya Pradesh", shortDescription: "Historic Rewa state capital" },
  { name: "Sagar", state: "Madhya Pradesh", shortDescription: "Lake city with university" },
  { name: "Burhanpur", state: "Madhya Pradesh", shortDescription: "Mughal city where Mumtaz died" },
  { name: "Datia", state: "Madhya Pradesh", shortDescription: "Seven-storey palace wonder" },
  { name: "Shivpuri", state: "Madhya Pradesh", shortDescription: "Former Scindia hunting grounds" },
  { name: "Chanderi", state: "Madhya Pradesh", shortDescription: "Handloom sarees and ruins" },
  { name: "Amarkantak", state: "Madhya Pradesh", shortDescription: "Source of Narmada and Son rivers" },
  { name: "Bhojpur", state: "Madhya Pradesh", shortDescription: "Bhojeshwar Temple with massive Shiva" },
  { name: "Vidisha", state: "Madhya Pradesh", shortDescription: "Ancient city near Sanchi" },
  { name: "Dhar", state: "Madhya Pradesh", shortDescription: "Historic Malwa capital" },
  { name: "Satpura", state: "Madhya Pradesh", shortDescription: "Tiger reserve with boat safaris" },
  
  // MAHARASHTRA
  { name: "Mumbai", state: "Maharashtra", shortDescription: "City of Dreams and financial capital" },
  { name: "Pune", state: "Maharashtra", shortDescription: "Cultural capital with pleasant climate" },
  { name: "Nagpur", state: "Maharashtra", shortDescription: "Orange city at center of India" },
  { name: "Nashik", state: "Maharashtra", shortDescription: "Wine capital and Kumbh Mela city" },
  { name: "Aurangabad", state: "Maharashtra", shortDescription: "Gateway to Ajanta Ellora caves" },
  { name: "Lonavala", state: "Maharashtra", shortDescription: "Hill station between Mumbai-Pune" },
  { name: "Mahabaleshwar", state: "Maharashtra", shortDescription: "Strawberry hill station" },
  { name: "Shirdi", state: "Maharashtra", shortDescription: "Sai Baba pilgrimage center" },
  { name: "Kolhapur", state: "Maharashtra", shortDescription: "Royal city with Mahalaxmi Temple" },
  { name: "Ajanta", state: "Maharashtra", shortDescription: "UNESCO Buddhist cave paintings" },
  { name: "Ellora", state: "Maharashtra", shortDescription: "UNESCO rock-cut cave temples" },
  { name: "Matheran", state: "Maharashtra", shortDescription: "Asia's only automobile-free hill station" },
  { name: "Alibaug", state: "Maharashtra", shortDescription: "Beach getaway from Mumbai" },
  { name: "Ganpatipule", state: "Maharashtra", shortDescription: "Beach town with Ganesh temple" },
  { name: "Panchgani", state: "Maharashtra", shortDescription: "Table Land hill station" },
  { name: "Lavasa", state: "Maharashtra", shortDescription: "Planned hill city near Pune" },
  { name: "Ratnagiri", state: "Maharashtra", shortDescription: "Alphonso mango capital and beaches" },
  { name: "Tarkarli", state: "Maharashtra", shortDescription: "Scuba diving and beach destination" },
  { name: "Tadoba", state: "Maharashtra", shortDescription: "Tiger reserve in Vidarbha" },
  { name: "Konkan", state: "Maharashtra", shortDescription: "Coastal paradise with pristine beaches" },
  { name: "Bhandardara", state: "Maharashtra", shortDescription: "Lake surrounded by Sahyadri hills" },
  { name: "Khandala", state: "Maharashtra", shortDescription: "Twin hill station of Lonavala" },
  { name: "Igatpuri", state: "Maharashtra", shortDescription: "Vipassana center and trekking" },
  { name: "Solapur", state: "Maharashtra", shortDescription: "Textile city with temples" },
  { name: "Sangli", state: "Maharashtra", shortDescription: "Turmeric trading center" },
  { name: "Satara", state: "Maharashtra", shortDescription: "Historic Maratha capital" },
  { name: "Ahmednagar", state: "Maharashtra", shortDescription: "Historic city with fort" },
  { name: "Amravati", state: "Maharashtra", shortDescription: "Gateway to Melghat" },
  { name: "Chandrapur", state: "Maharashtra", shortDescription: "Gateway to Tadoba" },
  { name: "Jalgaon", state: "Maharashtra", shortDescription: "Banana capital of India" },
  { name: "Latur", state: "Maharashtra", shortDescription: "Dal processing hub" },
  { name: "Nanded", state: "Maharashtra", shortDescription: "Sikh pilgrimage Hazur Sahib" },
  { name: "Wardha", state: "Maharashtra", shortDescription: "Sevagram Ashram of Gandhi" },
  { name: "Murud Janjira", state: "Maharashtra", shortDescription: "Sea fort fortress" },
  { name: "Diveagar", state: "Maharashtra", shortDescription: "Serene Konkan beach" },
  { name: "Harihareshwar", state: "Maharashtra", shortDescription: "Temple beach destination" },
  { name: "Malshej Ghat", state: "Maharashtra", shortDescription: "Waterfalls and flamingos" },
  { name: "Panhala", state: "Maharashtra", shortDescription: "Largest fort in Deccan" },
  { name: "Rajmachi", state: "Maharashtra", shortDescription: "Twin forts for trekking" },
  { name: "Sinhagad", state: "Maharashtra", shortDescription: "Historic fort near Pune" },
  { name: "Pratapgad", state: "Maharashtra", shortDescription: "Maratha fort of Shivaji" },
  { name: "Raigad", state: "Maharashtra", shortDescription: "Capital fort of Shivaji" },
  
  // MANIPUR
  { name: "Imphal", state: "Manipur", shortDescription: "Capital with Kangla Fort and Ima Keithel" },
  { name: "Loktak Lake", state: "Manipur", shortDescription: "Floating islands and Keibul Lamjao" },
  { name: "Moirang", state: "Manipur", shortDescription: "INA memorial and Loktak nearby" },
  { name: "Ukhrul", state: "Manipur", shortDescription: "Land of Shirui lily flower" },
  { name: "Churachandpur", state: "Manipur", shortDescription: "Hill district with tribal culture" },
  { name: "Senapati", state: "Manipur", shortDescription: "Hill district with Mao Gate" },
  { name: "Thoubal", state: "Manipur", shortDescription: "River valley district" },
  { name: "Bishnupur", state: "Manipur", shortDescription: "Historic district with traditions" },
  { name: "Moreh", state: "Manipur", shortDescription: "Border town with Myanmar" },
  { name: "Andro", state: "Manipur", shortDescription: "Tribal village with pottery" },
  
  // MEGHALAYA
  { name: "Shillong", state: "Meghalaya", shortDescription: "Scotland of the East with waterfalls" },
  { name: "Cherrapunji", state: "Meghalaya", shortDescription: "Wettest place on Earth with living root bridges" },
  { name: "Mawlynnong", state: "Meghalaya", shortDescription: "Cleanest village in Asia" },
  { name: "Dawki", state: "Meghalaya", shortDescription: "Crystal clear Umngot River" },
  { name: "Mawsynram", state: "Meghalaya", shortDescription: "Highest rainfall place with caves" },
  { name: "Nongriat", state: "Meghalaya", shortDescription: "Double decker living root bridge" },
  { name: "Tura", state: "Meghalaya", shortDescription: "Gateway to Nokrek National Park" },
  { name: "Jowai", state: "Meghalaya", shortDescription: "Krang Suri waterfall nearby" },
  { name: "Nongpoh", state: "Meghalaya", shortDescription: "Gateway to Meghalaya from Guwahati" },
  { name: "Laitlum Canyon", state: "Meghalaya", shortDescription: "Grand Canyon of India" },
  { name: "Mawphlang", state: "Meghalaya", shortDescription: "Sacred forest reserve" },
  { name: "Elephant Falls", state: "Meghalaya", shortDescription: "Three-tiered waterfall" },
  { name: "Nohkalikai Falls", state: "Meghalaya", shortDescription: "Tallest plunge waterfall in India" },
  { name: "Umiam Lake", state: "Meghalaya", shortDescription: "Man-made reservoir near Shillong" },
  
  // MIZORAM
  { name: "Aizawl", state: "Mizoram", shortDescription: "Hill capital with unique culture" },
  { name: "Lunglei", state: "Mizoram", shortDescription: "Second largest town with scenic beauty" },
  { name: "Champhai", state: "Mizoram", shortDescription: "Rice bowl of Mizoram near Myanmar" },
  { name: "Reiek", state: "Mizoram", shortDescription: "Mountain peak with heritage village" },
  { name: "Phawngpui", state: "Mizoram", shortDescription: "Blue Mountain highest peak" },
  { name: "Serchhip", state: "Mizoram", shortDescription: "Cleanest town with waterfalls" },
  { name: "Kolasib", state: "Mizoram", shortDescription: "Gateway from Assam" },
  { name: "Mamit", state: "Mizoram", shortDescription: "Wildlife sanctuary district" },
  { name: "Lawngtlai", state: "Mizoram", shortDescription: "Southern district with biodiversity" },
  { name: "Saiha", state: "Mizoram", shortDescription: "Mara district headquarters" },
  
  // NAGALAND
  { name: "Kohima", state: "Nagaland", shortDescription: "WWII memorial and Hornbill festival" },
  { name: "Dimapur", state: "Nagaland", shortDescription: "Commercial hub with Kachari ruins" },
  { name: "Mokokchung", state: "Nagaland", shortDescription: "Ao Naga cultural center" },
  { name: "Khonoma", state: "Nagaland", shortDescription: "Green village with warrior history" },
  { name: "Dzukou Valley", state: "Nagaland", shortDescription: "Valley of flowers trek" },
  { name: "Tuensang", state: "Nagaland", shortDescription: "Largest district with tribes" },
  { name: "Mon", state: "Nagaland", shortDescription: "Land of Konyak headhunters" },
  { name: "Wokha", state: "Nagaland", shortDescription: "Lotha Naga homeland" },
  { name: "Zunheboto", state: "Nagaland", shortDescription: "Sumi Naga district" },
  { name: "Phek", state: "Nagaland", shortDescription: "Shilloi Lake and Dzukou" },
  { name: "Longwa", state: "Nagaland", shortDescription: "Village on India-Myanmar border" },
  
  // ODISHA
  { name: "Bhubaneswar", state: "Odisha", shortDescription: "Temple City with ancient architecture" },
  { name: "Puri", state: "Odisha", shortDescription: "Sacred Jagannath Temple and beach" },
  { name: "Konark", state: "Odisha", shortDescription: "UNESCO Sun Temple masterpiece" },
  { name: "Cuttack", state: "Odisha", shortDescription: "Silver city with Barabati Fort" },
  { name: "Chilika Lake", state: "Odisha", shortDescription: "Asia's largest brackish water lagoon" },
  { name: "Gopalpur", state: "Odisha", shortDescription: "Beach resort with lighthouse" },
  { name: "Simlipal", state: "Odisha", shortDescription: "Tiger reserve with waterfalls" },
  { name: "Sambalpur", state: "Odisha", shortDescription: "Hirakud Dam and handlooms" },
  { name: "Rourkela", state: "Odisha", shortDescription: "Steel city in Sundargarh" },
  { name: "Berhampur", state: "Odisha", shortDescription: "Silk city of Odisha" },
  { name: "Balasore", state: "Odisha", shortDescription: "Coastal town with missile range" },
  { name: "Bhitarkanika", state: "Odisha", shortDescription: "Mangrove and crocodile sanctuary" },
  { name: "Dhauli", state: "Odisha", shortDescription: "Kalinga War site and peace pagoda" },
  { name: "Ratnagiri", state: "Odisha", shortDescription: "Buddhist excavation site" },
  { name: "Lalitgiri", state: "Odisha", shortDescription: "Buddhist diamond triangle" },
  { name: "Udayagiri", state: "Odisha", shortDescription: "Ancient Jain rock caves" },
  { name: "Chandipur", state: "Odisha", shortDescription: "Disappearing sea beach" },
  { name: "Jeypore", state: "Odisha", shortDescription: "Gateway to tribal areas" },
  { name: "Rayagada", state: "Odisha", shortDescription: "Tribal district with Dongriya Kondh" },
  { name: "Koraput", state: "Odisha", shortDescription: "Coffee and tribal culture" },
  { name: "Baripada", state: "Odisha", shortDescription: "Gateway to Simlipal" },
  { name: "Satkosia", state: "Odisha", shortDescription: "Tiger reserve gorge" },
  { name: "Debrigarh", state: "Odisha", shortDescription: "Wildlife sanctuary with Hirakud" },
  { name: "Angul", state: "Odisha", shortDescription: "Industrial town with Satkosia" },
  { name: "Kendrapara", state: "Odisha", shortDescription: "Gateway to Bhitarkanika" },
  { name: "Paradip", state: "Odisha", shortDescription: "Major port city" },
  
  // PUNJAB
  { name: "Amritsar", state: "Punjab", shortDescription: "Golden Temple and Wagah Border" },
  { name: "Ludhiana", state: "Punjab", shortDescription: "Manchester of India textile hub" },
  { name: "Jalandhar", state: "Punjab", shortDescription: "Sports goods manufacturing center" },
  { name: "Patiala", state: "Punjab", shortDescription: "Royal city with Qila Mubarak" },
  { name: "Bathinda", state: "Punjab", shortDescription: "Ancient fort city" },
  { name: "Mohali", state: "Punjab", shortDescription: "IT city with cricket stadium" },
  { name: "Kapurthala", state: "Punjab", shortDescription: "City of palaces and gardens" },
  { name: "Anandpur Sahib", state: "Punjab", shortDescription: "Sikh holy city birthplace of Khalsa" },
  { name: "Pathankot", state: "Punjab", shortDescription: "Gateway to Himachal and Jammu" },
  { name: "Hoshiarpur", state: "Punjab", shortDescription: "Wooden furniture hub" },
  { name: "Firozpur", state: "Punjab", shortDescription: "Historic border town" },
  { name: "Moga", state: "Punjab", shortDescription: "Agricultural hub" },
  { name: "Sangrur", state: "Punjab", shortDescription: "Historic town with gurudwaras" },
  { name: "Nawanshahr", state: "Punjab", shortDescription: "New city with industrial growth" },
  { name: "Fatehgarh Sahib", state: "Punjab", shortDescription: "Sikh pilgrimage center" },
  { name: "Ropar", state: "Punjab", shortDescription: "Indus Valley site and dam" },
  { name: "Tarn Taran", state: "Punjab", shortDescription: "Sikh shrine with large sarovar" },
  { name: "Faridkot", state: "Punjab", shortDescription: "Historic princely state" },
  { name: "Muktsar", state: "Punjab", shortDescription: "Maghi Mela pilgrimage" },
  { name: "Mansa", state: "Punjab", shortDescription: "Cotton region town" },
  
  // RAJASTHAN
  { name: "Udaipur", state: "Rajasthan", shortDescription: "City of Lakes with romantic palaces" },
  { name: "Jodhpur", state: "Rajasthan", shortDescription: "Blue City with Mehrangarh Fort" },
  { name: "Jaisalmer", state: "Rajasthan", shortDescription: "Golden City with desert safari" },
  { name: "Pushkar", state: "Rajasthan", shortDescription: "Sacred lake and camel fair" },
  { name: "Mount Abu", state: "Rajasthan", shortDescription: "Only hill station in Rajasthan" },
  { name: "Bikaner", state: "Rajasthan", shortDescription: "Camel country with Junagarh Fort" },
  { name: "Ajmer", state: "Rajasthan", shortDescription: "Sufi shrine of Khwaja Sahib" },
  { name: "Ranthambore", state: "Rajasthan", shortDescription: "Tiger reserve with ancient fort" },
  { name: "Chittorgarh", state: "Rajasthan", shortDescription: "Largest fort in India" },
  { name: "Bundi", state: "Rajasthan", shortDescription: "Step wells and blue houses" },
  { name: "Kumbhalgarh", state: "Rajasthan", shortDescription: "Great Wall of India fort" },
  { name: "Alwar", state: "Rajasthan", shortDescription: "Gateway to Sariska Tiger Reserve" },
  { name: "Bharatpur", state: "Rajasthan", shortDescription: "Keoladeo bird sanctuary UNESCO" },
  { name: "Sawai Madhopur", state: "Rajasthan", shortDescription: "Gateway to Ranthambore" },
  { name: "Shekhawati", state: "Rajasthan", shortDescription: "Open art gallery with havelis" },
  { name: "Mandawa", state: "Rajasthan", shortDescription: "Painted town of Shekhawati" },
  { name: "Ranakpur", state: "Rajasthan", shortDescription: "Intricate Jain temple complex" },
  { name: "Nathdwara", state: "Rajasthan", shortDescription: "Shrinathji Temple pilgrimage" },
  { name: "Kota", state: "Rajasthan", shortDescription: "Coaching hub on Chambal" },
  { name: "Sikar", state: "Rajasthan", shortDescription: "Shekhawati gateway town" },
  { name: "Jhunjhunu", state: "Rajasthan", shortDescription: "Rani Sati Temple town" },
  { name: "Pali", state: "Rajasthan", shortDescription: "Ranakpur temple gateway" },
  { name: "Barmer", state: "Rajasthan", shortDescription: "Desert town with handicrafts" },
  { name: "Dungarpur", state: "Rajasthan", shortDescription: "City of hills with palaces" },
  { name: "Banswara", state: "Rajasthan", shortDescription: "City of hundred islands" },
  { name: "Jhalawar", state: "Rajasthan", shortDescription: "Gangadhar Temple town" },
  { name: "Baran", state: "Rajasthan", shortDescription: "Hadoti region town" },
  { name: "Nagaur", state: "Rajasthan", shortDescription: "Fort and cattle fair town" },
  { name: "Churu", state: "Rajasthan", shortDescription: "Desert town with havelis" },
  { name: "Hanumangarh", state: "Rajasthan", shortDescription: "Archaeological site on Ghaggar" },
  { name: "Sirohi", state: "Rajasthan", shortDescription: "Gateway to Mount Abu" },
  { name: "Pratapgarh", state: "Rajasthan", shortDescription: "Tribal heritage town" },
  { name: "Deogarh", state: "Rajasthan", shortDescription: "Heritage town with palace" },
  { name: "Neemrana", state: "Rajasthan", shortDescription: "Fort palace heritage hotel" },
  { name: "Sariska", state: "Rajasthan", shortDescription: "Tiger reserve near Delhi" },
  { name: "Osian", state: "Rajasthan", shortDescription: "Khajuraho of Rajasthan temples" },
  { name: "Khimsar", state: "Rajasthan", shortDescription: "Desert fort and dunes" },
  { name: "Dausa", state: "Rajasthan", shortDescription: "Historic town with temples" },
  
  // SIKKIM
  { name: "Gangtok", state: "Sikkim", shortDescription: "Capital with monasteries and Kanchenjunga views" },
  { name: "Pelling", state: "Sikkim", shortDescription: "Kanchenjunga viewpoint and monasteries" },
  { name: "Lachen", state: "Sikkim", shortDescription: "Gateway to Gurudongmar Lake" },
  { name: "Lachung", state: "Sikkim", shortDescription: "Gateway to Yumthang Valley" },
  { name: "Yumthang Valley", state: "Sikkim", shortDescription: "Valley of flowers in North Sikkim" },
  { name: "Tsomgo Lake", state: "Sikkim", shortDescription: "Sacred glacial lake on Indo-China border" },
  { name: "Nathula Pass", state: "Sikkim", shortDescription: "Indo-China border pass" },
  { name: "Ravangla", state: "Sikkim", shortDescription: "Buddha Park with giant statue" },
  { name: "Namchi", state: "Sikkim", shortDescription: "Religious site with Char Dham" },
  { name: "Zuluk", state: "Sikkim", shortDescription: "Silk route with zigzag roads" },
  { name: "Gurudongmar Lake", state: "Sikkim", shortDescription: "Sacred high altitude lake" },
  { name: "Yuksom", state: "Sikkim", shortDescription: "First capital and Goechala base" },
  { name: "Rumtek", state: "Sikkim", shortDescription: "Famous Kagyu monastery" },
  { name: "Pemayangtse", state: "Sikkim", shortDescription: "Ancient Nyingmapa monastery" },
  { name: "Khecheopalri Lake", state: "Sikkim", shortDescription: "Wish-fulfilling sacred lake" },
  { name: "Mangan", state: "Sikkim", shortDescription: "North Sikkim headquarters" },
  { name: "Jorethang", state: "Sikkim", shortDescription: "South Sikkim trading town" },
  { name: "Singtam", state: "Sikkim", shortDescription: "Commercial hub on Teesta" },
  
  // TAMIL NADU
  { name: "Chennai", state: "Tamil Nadu", shortDescription: "Cultural capital with Marina Beach" },
  { name: "Madurai", state: "Tamil Nadu", shortDescription: "Temple city with Meenakshi Temple" },
  { name: "Coimbatore", state: "Tamil Nadu", shortDescription: "Manchester of South India" },
  { name: "Tiruchirappalli", state: "Tamil Nadu", shortDescription: "Rock Fort Temple city" },
  { name: "Ooty", state: "Tamil Nadu", shortDescription: "Queen of Nilgiris hill stations" },
  { name: "Kodaikanal", state: "Tamil Nadu", shortDescription: "Princess of Hill Stations" },
  { name: "Mahabalipuram", state: "Tamil Nadu", shortDescription: "UNESCO shore temples" },
  { name: "Pondicherry", state: "Tamil Nadu", shortDescription: "French colonial heritage town" },
  { name: "Kanyakumari", state: "Tamil Nadu", shortDescription: "Southernmost tip of India" },
  { name: "Thanjavur", state: "Tamil Nadu", shortDescription: "UNESCO Brihadeeswara Temple" },
  { name: "Rameswaram", state: "Tamil Nadu", shortDescription: "Sacred island pilgrimage" },
  { name: "Coonoor", state: "Tamil Nadu", shortDescription: "Tea estates in Nilgiris" },
  { name: "Yelagiri", state: "Tamil Nadu", shortDescription: "Offbeat hill station" },
  { name: "Yercaud", state: "Tamil Nadu", shortDescription: "Jewel of South with lake" },
  { name: "Dhanushkodi", state: "Tamil Nadu", shortDescription: "Ghost town on India's tip" },
  { name: "Valparai", state: "Tamil Nadu", shortDescription: "Tea estate hill station" },
  { name: "Kumbakonam", state: "Tamil Nadu", shortDescription: "Temple town with Mahamaham" },
  { name: "Chidambaram", state: "Tamil Nadu", shortDescription: "Nataraja Temple of cosmic dance" },
  { name: "Salem", state: "Tamil Nadu", shortDescription: "Steel city with Yercaud nearby" },
  { name: "Tirunelveli", state: "Tamil Nadu", shortDescription: "Ancient temple town" },
  { name: "Vellore", state: "Tamil Nadu", shortDescription: "Fort city with Golden Temple" },
  { name: "Erode", state: "Tamil Nadu", shortDescription: "Textile and turmeric hub" },
  { name: "Thoothukudi", state: "Tamil Nadu", shortDescription: "Port city and pearl diving" },
  { name: "Dindigul", state: "Tamil Nadu", shortDescription: "Lock making and biryani city" },
  { name: "Tiruvannamalai", state: "Tamil Nadu", shortDescription: "Arunachaleswarar Temple pilgrimage" },
  { name: "Nagapattinam", state: "Tamil Nadu", shortDescription: "Buddhist heritage port city" },
  { name: "Karaikudi", state: "Tamil Nadu", shortDescription: "Chettinad mansion town" },
  { name: "Kanchipuram", state: "Tamil Nadu", shortDescription: "Silk saree and temple city" },
  { name: "Tirupur", state: "Tamil Nadu", shortDescription: "Knitwear capital of India" },
  { name: "Hosur", state: "Tamil Nadu", shortDescription: "Industrial town near Bangalore" },
  { name: "Pollachi", state: "Tamil Nadu", shortDescription: "Coconut hub near Anamalai" },
  { name: "Courtallam", state: "Tamil Nadu", shortDescription: "Spa of South India waterfalls" },
  { name: "Mudumalai", state: "Tamil Nadu", shortDescription: "Tiger reserve in Nilgiris" },
  { name: "Hogenakkal", state: "Tamil Nadu", shortDescription: "Niagara of India falls" },
  { name: "Kolli Hills", state: "Tamil Nadu", shortDescription: "70 hairpin bends hill station" },
  { name: "Javadi Hills", state: "Tamil Nadu", shortDescription: "Tribal hill region" },
  { name: "Vedanthangal", state: "Tamil Nadu", shortDescription: "Bird sanctuary near Chennai" },
  
  // TELANGANA
  { name: "Warangal", state: "Telangana", shortDescription: "Kakatiya kingdom heritage" },
  { name: "Nizamabad", state: "Telangana", shortDescription: "Historic forts and temples" },
  { name: "Karimnagar", state: "Telangana", shortDescription: "Silver filigree work center" },
  { name: "Khammam", state: "Telangana", shortDescription: "Tribal culture and forests" },
  { name: "Nagarjunasagar", state: "Telangana", shortDescription: "Dam and Buddhist ruins" },
  { name: "Ramoji Film City", state: "Telangana", shortDescription: "World's largest film studio complex" },
  { name: "Adilabad", state: "Telangana", shortDescription: "Tribal region with waterfalls" },
  { name: "Mahbubnagar", state: "Telangana", shortDescription: "Historic town with pillarless mosque" },
  { name: "Nalgonda", state: "Telangana", shortDescription: "Historic fort town" },
  { name: "Medak", state: "Telangana", shortDescription: "Church and fort town" },
  { name: "Siddipet", state: "Telangana", shortDescription: "Growing city with temples" },
  { name: "Bhongir", state: "Telangana", shortDescription: "Egg-shaped fort hill" },
  { name: "Pochampally", state: "Telangana", shortDescription: "Ikat weaving village" },
  { name: "Yadagirigutta", state: "Telangana", shortDescription: "Lakshmi Narasimha Temple" },
  { name: "Basara", state: "Telangana", shortDescription: "Saraswati Temple pilgrimage" },
  { name: "Nagarjunakonda", state: "Telangana", shortDescription: "Buddhist island museum" },
  
  // TRIPURA
  { name: "Agartala", state: "Tripura", shortDescription: "Capital with Ujjayanta Palace" },
  { name: "Udaipur", state: "Tripura", shortDescription: "Lake town with Tripura Sundari Temple" },
  { name: "Neermahal", state: "Tripura", shortDescription: "Water palace in Rudrasagar Lake" },
  { name: "Unakoti", state: "Tripura", shortDescription: "Rock carvings pilgrimage site" },
  { name: "Jampui Hills", state: "Tripura", shortDescription: "Orange festival location" },
  { name: "Sepahijala", state: "Tripura", shortDescription: "Wildlife sanctuary with primates" },
  { name: "Amarpur", state: "Tripura", shortDescription: "Gateway to Dumbur Lake" },
  { name: "Dharmanagar", state: "Tripura", shortDescription: "North Tripura headquarters" },
  { name: "Kailashahar", state: "Tripura", shortDescription: "Historic temple town" },
  { name: "Belonia", state: "Tripura", shortDescription: "Border town with Bangladesh" },
  
  // UTTAR PRADESH
  { name: "Varanasi", state: "Uttar Pradesh", shortDescription: "Spiritual capital on sacred Ganges" },
  { name: "Agra", state: "Uttar Pradesh", shortDescription: "Home to iconic Taj Mahal" },
  { name: "Lucknow", state: "Uttar Pradesh", shortDescription: "City of Nawabs with rich culture" },
  { name: "Prayagraj", state: "Uttar Pradesh", shortDescription: "Confluence of three rivers and Kumbh Mela" },
  { name: "Mathura", state: "Uttar Pradesh", shortDescription: "Birthplace of Lord Krishna" },
  { name: "Vrindavan", state: "Uttar Pradesh", shortDescription: "Sacred town of Radha-Krishna" },
  { name: "Ayodhya", state: "Uttar Pradesh", shortDescription: "Birthplace of Lord Rama" },
  { name: "Fatehpur Sikri", state: "Uttar Pradesh", shortDescription: "UNESCO Mughal ghost city" },
  { name: "Sarnath", state: "Uttar Pradesh", shortDescription: "Where Buddha gave first sermon" },
  { name: "Chitrakoot", state: "Uttar Pradesh", shortDescription: "Rama's exile spot with temples" },
  { name: "Noida", state: "Uttar Pradesh", shortDescription: "NCR city with modern infrastructure" },
  { name: "Greater Noida", state: "Uttar Pradesh", shortDescription: "Formula 1 circuit and expo city" },
  { name: "Ghaziabad", state: "Uttar Pradesh", shortDescription: "Gateway to UP from Delhi" },
  { name: "Kanpur", state: "Uttar Pradesh", shortDescription: "Industrial city with leather industry" },
  { name: "Jhansi", state: "Uttar Pradesh", shortDescription: "Fort city of Rani Lakshmibai" },
  { name: "Aligarh", state: "Uttar Pradesh", shortDescription: "Lock industry and university town" },
  { name: "Meerut", state: "Uttar Pradesh", shortDescription: "Sports goods and 1857 mutiny" },
  { name: "Gorakhpur", state: "Uttar Pradesh", shortDescription: "Gateway to Nepal" },
  { name: "Kushinagar", state: "Uttar Pradesh", shortDescription: "Where Buddha attained Mahaparinirvana" },
  { name: "Bareilly", state: "Uttar Pradesh", shortDescription: "Zari-zardozi craft center" },
  { name: "Moradabad", state: "Uttar Pradesh", shortDescription: "Brass city of India" },
  { name: "Saharanpur", state: "Uttar Pradesh", shortDescription: "Wood carving center" },
  { name: "Firozabad", state: "Uttar Pradesh", shortDescription: "Glass bangle city" },
  { name: "Mirzapur", state: "Uttar Pradesh", shortDescription: "Carpet weaving and Vindhyachal Temple" },
  { name: "Sultanpur", state: "Uttar Pradesh", shortDescription: "Historic town on Gomti" },
  { name: "Basti", state: "Uttar Pradesh", shortDescription: "Ancient town with temples" },
  { name: "Azamgarh", state: "Uttar Pradesh", shortDescription: "Black pottery center" },
  { name: "Unnao", state: "Uttar Pradesh", shortDescription: "Leather industry hub" },
  { name: "Rae Bareli", state: "Uttar Pradesh", shortDescription: "Political significance town" },
  { name: "Faizabad", state: "Uttar Pradesh", shortDescription: "Gateway to Ayodhya" },
  { name: "Shravasti", state: "Uttar Pradesh", shortDescription: "Buddhist pilgrimage site" },
  { name: "Etawah", state: "Uttar Pradesh", shortDescription: "Lion safari and chambal" },
  { name: "Mainpuri", state: "Uttar Pradesh", shortDescription: "Historic town in Doab" },
  { name: "Budaun", state: "Uttar Pradesh", shortDescription: "Jama Masjid and Iqbal Minar" },
  { name: "Shahjahanpur", state: "Uttar Pradesh", shortDescription: "Freedom fighter Ram Prasad Bismil's town" },
  { name: "Rampur", state: "Uttar Pradesh", shortDescription: "Raza Library heritage" },
  { name: "Banda", state: "Uttar Pradesh", shortDescription: "Chitrakoot gateway" },
  { name: "Bahraich", state: "Uttar Pradesh", shortDescription: "Ghaghra riverfront town" },
  { name: "Vindhyachal", state: "Uttar Pradesh", shortDescription: "Vindhyavasini Devi Temple" },
  
  // UTTARAKHAND
  { name: "Rishikesh", state: "Uttarakhand", shortDescription: "Yoga capital and adventure hub" },
  { name: "Haridwar", state: "Uttarakhand", shortDescription: "Gateway to Char Dham and Ganga Aarti" },
  { name: "Dehradun", state: "Uttarakhand", shortDescription: "Capital city in Doon Valley" },
  { name: "Nainital", state: "Uttarakhand", shortDescription: "Lake district hill station" },
  { name: "Mussoorie", state: "Uttarakhand", shortDescription: "Queen of Hills near Dehradun" },
  { name: "Jim Corbett", state: "Uttarakhand", shortDescription: "India's first tiger reserve" },
  { name: "Auli", state: "Uttarakhand", shortDescription: "Skiing destination with Himalayan views" },
  { name: "Valley of Flowers", state: "Uttarakhand", shortDescription: "UNESCO alpine flowers sanctuary" },
  { name: "Kedarnath", state: "Uttarakhand", shortDescription: "Sacred Jyotirlinga in Himalayas" },
  { name: "Badrinath", state: "Uttarakhand", shortDescription: "Sacred Char Dham pilgrimage" },
  { name: "Gangotri", state: "Uttarakhand", shortDescription: "Source of River Ganga" },
  { name: "Yamunotri", state: "Uttarakhand", shortDescription: "Source of River Yamuna" },
  { name: "Almora", state: "Uttarakhand", shortDescription: "Cultural hub of Kumaon hills" },
  { name: "Ranikhet", state: "Uttarakhand", shortDescription: "Queen's meadow hill station" },
  { name: "Bhimtal", state: "Uttarakhand", shortDescription: "Largest lake in Kumaon" },
  { name: "Lansdowne", state: "Uttarakhand", shortDescription: "Quiet cantonment hill station" },
  { name: "Chopta", state: "Uttarakhand", shortDescription: "Mini Switzerland with Tungnath" },
  { name: "Binsar", state: "Uttarakhand", shortDescription: "Wildlife sanctuary with Himalayan views" },
  { name: "Mukteshwar", state: "Uttarakhand", shortDescription: "Cliff hanging temple with views" },
  { name: "Kausani", state: "Uttarakhand", shortDescription: "Tea gardens with Himalayan panorama" },
  { name: "Chakrata", state: "Uttarakhand", shortDescription: "Offbeat hill station with Tiger Falls" },
  { name: "Pithoragarh", state: "Uttarakhand", shortDescription: "Little Kashmir of Uttarakhand" },
  { name: "Munsiyari", state: "Uttarakhand", shortDescription: "Gateway to Milam Glacier" },
  { name: "Chaukori", state: "Uttarakhand", shortDescription: "Tea gardens with Panchachuli views" },
  { name: "Dhanaulti", state: "Uttarakhand", shortDescription: "Serene hill station near Mussoorie" },
  { name: "Kanatal", state: "Uttarakhand", shortDescription: "Adventure activities and camping" },
  { name: "Tehri", state: "Uttarakhand", shortDescription: "Dam and water sports" },
  { name: "Devprayag", state: "Uttarakhand", shortDescription: "Confluence of Alaknanda and Bhagirathi" },
  { name: "Rudraprayag", state: "Uttarakhand", shortDescription: "Confluence of Alaknanda and Mandakini" },
  { name: "Chamoli", state: "Uttarakhand", shortDescription: "Gateway to Badrinath" },
  { name: "Gopeshwar", state: "Uttarakhand", shortDescription: "Headquarters of Chamoli" },
  { name: "Joshimath", state: "Uttarakhand", shortDescription: "Gateway to Badrinath and Auli" },
  { name: "Uttarkashi", state: "Uttarakhand", shortDescription: "Gateway to Gangotri" },
  { name: "Sattal", state: "Uttarakhand", shortDescription: "Seven interconnected lakes" },
  { name: "Naukuchiatal", state: "Uttarakhand", shortDescription: "Nine-cornered lake" },
  { name: "Khirsu", state: "Uttarakhand", shortDescription: "Oak and deodar forest retreat" },
  { name: "Pauri", state: "Uttarakhand", shortDescription: "District headquarters with views" },
  { name: "Haldwani", state: "Uttarakhand", shortDescription: "Gateway to Kumaon" },
  { name: "Roorkee", state: "Uttarakhand", shortDescription: "IIT and Ganges Canal town" },
  { name: "Kotdwar", state: "Uttarakhand", shortDescription: "Gateway to Lansdowne" },
  { name: "Kashipur", state: "Uttarakhand", shortDescription: "Industrial town with temples" },
  
  // WEST BENGAL
  { name: "Kolkata", state: "West Bengal", shortDescription: "City of Joy with colonial heritage" },
  { name: "Darjeeling", state: "West Bengal", shortDescription: "Queen of Hills with tea gardens" },
  { name: "Siliguri", state: "West Bengal", shortDescription: "Gateway to Northeast and Darjeeling" },
  { name: "Kalimpong", state: "West Bengal", shortDescription: "Hill town with Buddhist monasteries" },
  { name: "Sundarbans", state: "West Bengal", shortDescription: "UNESCO mangrove with Royal Bengal Tigers" },
  { name: "Shantiniketan", state: "West Bengal", shortDescription: "Tagore's university and art" },
  { name: "Digha", state: "West Bengal", shortDescription: "Popular beach near Kolkata" },
  { name: "Murshidabad", state: "West Bengal", shortDescription: "Nawabi heritage city" },
  { name: "Bishnupur", state: "West Bengal", shortDescription: "Terracotta temples UNESCO" },
  { name: "Kurseong", state: "West Bengal", shortDescription: "Land of white orchids" },
  { name: "Mirik", state: "West Bengal", shortDescription: "Lake surrounded by tea gardens" },
  { name: "Lava", state: "West Bengal", shortDescription: "Kanchenjunga views and forest" },
  { name: "Sandakphu", state: "West Bengal", shortDescription: "Highest peak with four 8000m peaks view" },
  { name: "Mandarmani", state: "West Bengal", shortDescription: "Beach with longest driveable stretch" },
  { name: "Bakkhali", state: "West Bengal", shortDescription: "Quiet beach destination" },
  { name: "Durgapur", state: "West Bengal", shortDescription: "Steel city with industries" },
  { name: "Asansol", state: "West Bengal", shortDescription: "Coal mining region" },
  { name: "Howrah", state: "West Bengal", shortDescription: "Industrial suburb of Kolkata" },
  { name: "Kharagpur", state: "West Bengal", shortDescription: "IIT and railway junction" },
  { name: "Haldia", state: "West Bengal", shortDescription: "Port and petrochemical hub" },
  { name: "Malda", state: "West Bengal", shortDescription: "Mango capital with Gaur ruins" },
  { name: "Cooch Behar", state: "West Bengal", shortDescription: "Royal palace and heritage" },
  { name: "Jalpaiguri", state: "West Bengal", shortDescription: "Gateway to Dooars" },
  { name: "Alipurduar", state: "West Bengal", shortDescription: "Gateway to Buxa Tiger Reserve" },
  { name: "Balurghat", state: "West Bengal", shortDescription: "Border town in South Dinajpur" },
  { name: "Bolpur", state: "West Bengal", shortDescription: "Home of Shantiniketan" },
  { name: "Tarapith", state: "West Bengal", shortDescription: "Tantric pilgrimage site" },
  { name: "Mayapur", state: "West Bengal", shortDescription: "ISKCON headquarters" },
  { name: "Navadwip", state: "West Bengal", shortDescription: "Birthplace of Chaitanya Mahaprabhu" },
  { name: "Diamond Harbour", state: "West Bengal", shortDescription: "Picnic spot on Hooghly" },
  { name: "Sagar Island", state: "West Bengal", shortDescription: "Gangasagar Mela pilgrimage" },
  { name: "Purulia", state: "West Bengal", shortDescription: "Chhau dance and Ayodhya Hills" },
  { name: "Bankura", state: "West Bengal", shortDescription: "Terracotta and Bishnupur" },
  { name: "Hooghly", state: "West Bengal", shortDescription: "Colonial riverside towns" },
  { name: "Chinsurah", state: "West Bengal", shortDescription: "Dutch and Danish heritage" },
  { name: "Bandel", state: "West Bengal", shortDescription: "Portuguese church town" },
  { name: "Burdwan", state: "West Bengal", shortDescription: "Historic town with university" },
  { name: "Krishnanagar", state: "West Bengal", shortDescription: "Clay modeling center" },
  { name: "Ghoom", state: "West Bengal", shortDescription: "Highest railway station on DHR" },
  { name: "Jaldapara", state: "West Bengal", shortDescription: "One-horned rhino sanctuary" },
  { name: "Gorumara", state: "West Bengal", shortDescription: "National park in Dooars" },
  { name: "Buxa", state: "West Bengal", shortDescription: "Tiger reserve with fort" },
  { name: "Samsing", state: "West Bengal", shortDescription: "Orange orchards in Dooars" },
  { name: "Rishop", state: "West Bengal", shortDescription: "Kanchenjunga sunrise point" },
  { name: "Lolegaon", state: "West Bengal", shortDescription: "Canopy walk and views" },
  { name: "Phalut", state: "West Bengal", shortDescription: "Second highest peak in WB" },
  { name: "Tonglu", state: "West Bengal", shortDescription: "Trek to Sandakphu" },
  { name: "Tiger Hill", state: "West Bengal", shortDescription: "Sunrise over Kanchenjunga" },
  
  // UNION TERRITORIES
  { name: "Delhi", state: "Delhi", shortDescription: "Capital city with monuments and modernity" },
  { name: "New Delhi", state: "Delhi", shortDescription: "Lutyens' Delhi with government buildings" },
  { name: "Old Delhi", state: "Delhi", shortDescription: "Mughal heritage and street food" },
  { name: "Connaught Place", state: "Delhi", shortDescription: "Central business district" },
  { name: "Hauz Khas", state: "Delhi", shortDescription: "Historic complex with urban village" },
  { name: "Mehrauli", state: "Delhi", shortDescription: "Qutub Minar and archaeological park" },
  { name: "Chandni Chowk", state: "Delhi", shortDescription: "Historic market and food street" },
  { name: "Lodhi Garden", state: "Delhi", shortDescription: "Historic tombs in green park" },
  { name: "India Gate", state: "Delhi", shortDescription: "War memorial and promenade" },
  { name: "Red Fort", state: "Delhi", shortDescription: "UNESCO Mughal fort" },
  { name: "Humayun's Tomb", state: "Delhi", shortDescription: "UNESCO Mughal garden tomb" },
  { name: "Akshardham", state: "Delhi", shortDescription: "Modern Hindu temple complex" },
  { name: "Lotus Temple", state: "Delhi", shortDescription: "Bahai House of Worship" },
  
  { name: "Port Blair", state: "Andaman & Nicobar", shortDescription: "Capital with Cellular Jail" },
  { name: "Havelock Island", state: "Andaman & Nicobar", shortDescription: "Radhanagar Beach paradise" },
  { name: "Neil Island", state: "Andaman & Nicobar", shortDescription: "Natural bridge and beaches" },
  { name: "Ross Island", state: "Andaman & Nicobar", shortDescription: "British era ruins" },
  { name: "Baratang", state: "Andaman & Nicobar", shortDescription: "Limestone caves and mangroves" },
  { name: "Diglipur", state: "Andaman & Nicobar", shortDescription: "Saddle Peak and turtle nesting" },
  { name: "Long Island", state: "Andaman & Nicobar", shortDescription: "Pristine beaches and diving" },
  { name: "Rangat", state: "Andaman & Nicobar", shortDescription: "Mangrove creeks and beaches" },
  { name: "Little Andaman", state: "Andaman & Nicobar", shortDescription: "Surfing and elephants" },
  
  { name: "Puducherry", state: "Puducherry", shortDescription: "French colonial charm and beaches" },
  { name: "Auroville", state: "Puducherry", shortDescription: "Experimental universal township" },
  { name: "Paradise Beach", state: "Puducherry", shortDescription: "Secluded beach by boat" },
  { name: "Serenity Beach", state: "Puducherry", shortDescription: "Surfing and rock beach" },
  { name: "Karaikal", state: "Puducherry", shortDescription: "French enclave with temple" },
  { name: "Mahe", state: "Puducherry", shortDescription: "French territory in Kerala" },
  { name: "Yanam", state: "Puducherry", shortDescription: "French territory in AP" },
  
  { name: "Daman", state: "Dadra and Nagar Haveli and Daman and Diu", shortDescription: "Portuguese heritage and beaches" },
  { name: "Silvassa", state: "Dadra and Nagar Haveli and Daman and Diu", shortDescription: "Capital with tribal culture" },
  
  { name: "Kavaratti", state: "Lakshadweep", shortDescription: "Capital island with lagoons" },
  { name: "Agatti", state: "Lakshadweep", shortDescription: "Airport island with coral reefs" },
  { name: "Bangaram", state: "Lakshadweep", shortDescription: "Uninhabited island resort" },
  { name: "Minicoy", state: "Lakshadweep", shortDescription: "Lighthouse and Maldivian culture" },
  { name: "Kadmat", state: "Lakshadweep", shortDescription: "Water sports island" },
  { name: "Kalpeni", state: "Lakshadweep", shortDescription: "Three islands with lagoon" },
  
  { name: "Srinagar", state: "Jammu & Kashmir", shortDescription: "Dal Lake houseboats and gardens" },
  { name: "Gulmarg", state: "Jammu & Kashmir", shortDescription: "Skiing and world's highest gondola" },
  { name: "Pahalgam", state: "Jammu & Kashmir", shortDescription: "Valley of Shepherds and Amarnath base" },
  { name: "Sonmarg", state: "Jammu & Kashmir", shortDescription: "Meadow of Gold with Thajiwas Glacier" },
  { name: "Jammu", state: "Jammu & Kashmir", shortDescription: "City of Temples and Vaishno Devi base" },
  { name: "Patnitop", state: "Jammu & Kashmir", shortDescription: "Hill station between Jammu-Srinagar" },
  { name: "Vaishno Devi", state: "Jammu & Kashmir", shortDescription: "Sacred shrine in Trikuta Hills" },
  { name: "Doodhpathri", state: "Jammu & Kashmir", shortDescription: "Valley of Milk meadows" },
  { name: "Yusmarg", state: "Jammu & Kashmir", shortDescription: "Meadow of Jesus with pine forests" },
  { name: "Betaab Valley", state: "Jammu & Kashmir", shortDescription: "Bollywood film location valley" },
  { name: "Aru Valley", state: "Jammu & Kashmir", shortDescription: "Meadows and trekking base" },
  { name: "Aharbal", state: "Jammu & Kashmir", shortDescription: "Waterfall destination" },
  { name: "Kokernag", state: "Jammu & Kashmir", shortDescription: "Freshwater springs and trout" },
  { name: "Verinag", state: "Jammu & Kashmir", shortDescription: "Source of Jhelum River" },
  { name: "Kupwara", state: "Jammu & Kashmir", shortDescription: "Apple orchards and meadows" },
  { name: "Bhaderwah", state: "Jammu & Kashmir", shortDescription: "Mini Kashmir in Jammu" },
  { name: "Kishtwar", state: "Jammu & Kashmir", shortDescription: "Sapphire mines and trekking" },
  { name: "Sanasar", state: "Jammu & Kashmir", shortDescription: "Cup-shaped meadow" },
  { name: "Sinthan Top", state: "Jammu & Kashmir", shortDescription: "Mountain pass with views" },
  { name: "Daksum", state: "Jammu & Kashmir", shortDescription: "Pine forest retreat" },
];

async function seedDestinations() {
  console.log("Seeding destinations...");
  
  try {
    const existing = await storage.getAllDestinations();
    if (existing.length > 0) {
      console.log(`Found ${existing.length} existing destinations, skipping seed.`);
      return;
    }

    for (const destination of destinationsData) {
      const fullDestination = {
        name: destination.name,
        state: destination.state,
        shortDescription: destination.shortDescription,
        detailedInsight: destination.detailedInsight || generateDetailedInsight(destination.name, destination.state, destination.shortDescription),
        highlights: destination.highlights || generateHighlights(destination.shortDescription),
        imageUrl: destination.imageUrl || DEFAULT_IMAGE,
        bestSeason: destination.bestSeason || "October to March",
        isFeatured: destination.isFeatured || false,
        featuredDate: destination.featuredDate,
      };
      await storage.createDestination(fullDestination);
    }
    
    console.log(`Successfully seeded ${destinationsData.length} destinations!`);
  } catch (error) {
    console.error("Error seeding destinations:", error);
    throw error;
  }
}

export { seedDestinations };
